apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: nginx:latest
          name: guestbook-ui
          ports:
            - containerPort: 80
          resources:              # Add this section
            requests:             # Minimum resources needed
              memory: "64Mi"
              cpu: "50m"
            limits:               # Maximum resources allowed
              memory: "128Mi"
              cpu: "100m"